/* eslint-disable @typescript-eslint/no-unused-vars */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function seedData() {
  try {
    const currentDate = new Date();
    const roles = await prisma.roles.createMany({
      data: [
        { name: "Admin", code: "admin" },
        { name: "Service Provider", code: "service_provider" },
        { name: "Buyer", code: "buyer" },
      ],
      skipDuplicates: true,
    });
    const platforms = await prisma.platforms.createMany({
      data: [
        {
          name: "Browser",
          status: 1,
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          name: "Console ",
          status: 1,
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          name: "Mobile/Tablet",
          status: 1,
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          name: "PC/Mac",
          status: 1,
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          name: "Social ",
          status: 1,
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          name: "Streaming ",
          status: 1,
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          name: "VR/AR",
          status: 1,
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          name: "Not Applicable",
          status: 1,
          createdAt: currentDate,
          updatedAt: currentDate,
        },
      ],
    });

    // const services = await prisma.services.createMany({
    //   data: [
    //     {
    //       id: 1,
    //       groupId: 1,
    //       serviceName: "Animation",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 2, 
    //       groupId: 1,
    //       serviceName: "Art", 
    //       createdAt: currentDate, 
    //       updatedAt: currentDate 
    //     },
    //     { id: 3,
    //       groupId: 1,
    //       serviceName: "Audio",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 4,
    //       groupId: 1,
    //       serviceName: "Cinematics",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 5,
    //       groupId: 1,
    //       serviceName: "Motion Capture",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 6,
    //       groupId: 1,
    //       serviceName: "Narrative Design",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 7,
    //       groupId: 1,
    //       serviceName: "Photogrammetry",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 8,
    //       groupId: 1,
    //       serviceName: "Pre-Visual",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 9,
    //       groupId: 1,
    //       serviceName: "Technical Art",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 10,
    //       groupId: 1,
    //       serviceName: "UI/UX",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 11,
    //       groupId: 1,
    //       serviceName: "VFX",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 12,
    //       groupId: 2,
    //       serviceName: "AI",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 13,
    //       groupId: 2,
    //       serviceName: "Cloud Services",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 14,
    //       groupId: 2,
    //       serviceName: "Engineering (Work for hire)",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     {id: 15,
    //       groupId: 2,
    //       serviceName: "Middleware & Tools",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 16,
    //       groupId: 2,
    //       serviceName: "Porting",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 17,
    //       groupId: 2,
    //       serviceName: "Live Services",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 18,
    //       groupId: 3,
    //       serviceName: "Co-Development",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 19,
    //       groupId: 3,
    //       serviceName: "Culturalization",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 20,
    //       groupId: 3,
    //       serviceName: "Design",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 21,
    //       groupId: 3,
    //       serviceName: "Full SKU",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 22,
    //       groupId: 3,
    //       serviceName: "Ptototyping",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 23,
    //       groupId: 3,
    //       serviceName: "Localization",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 24,
    //       groupId: 3,
    //       serviceName: "Quality Assurance",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 25,
    //       groupId: 4,
    //       serviceName: "Business Development",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 26,
    //       groupId: 4,
    //       serviceName: "Consulting",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 27,
    //       groupId: 4,
    //       serviceName: "Player Research",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 28,
    //       groupId: 4,
    //       serviceName: "Full SKU Development",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 29,
    //       groupId: 4,
    //       serviceName: "Marketing",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 30,
    //       groupId: 4,
    //       serviceName: "Supplimentary Services",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 31,
    //       groupId: 4,
    //       serviceName: "Recruitment",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 32,
    //       groupId: 4,
    //       serviceName: "Training, Coaching, Education",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 33,
    //       groupId: 4,
    //       serviceName: "Community Management",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //     { id: 34,
    //       groupId: 4,
    //       serviceName: "Research & Development",
    //       createdAt: currentDate,
    //       updatedAt: currentDate,
    //     },
    //   ],
    // });

    const capabilities = await prisma.capabilities.createMany({
      data: [
        {
          serviceId: 1,
          capabilityName: "3D",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 1,
          capabilityName: "2D",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 1,
          capabilityName: "Keyframe",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 1,
          capabilityName: "Facial Animation",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 1,
          capabilityName: "Motion Design",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 1,
          capabilityName: "Creature Animation",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 1,
          capabilityName: "Technical Animation",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 2,
          capabilityName: "3D",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 2,
          capabilityName: "2D",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 2,
          capabilityName: "Environments",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 2,
          capabilityName: "Props",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 2,
          capabilityName: "Foliage",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 2,
          capabilityName: "Character",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 2,
          capabilityName: "Creature",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 2,
          capabilityName: "Vehicles",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 2,
          capabilityName: "Weapons",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 2,
          capabilityName: "Concepts",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 2,
          capabilityName: "Graphic Design",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 2,
          capabilityName: "Creative Design",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 3,
          capabilityName: "Composition",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 3,
          capabilityName: "Environmental",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 3,
          capabilityName: "Vocal",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 3,
          capabilityName: "Foley",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 3,
          capabilityName: "Procedural",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 3,
          capabilityName: "Music Sourcing & Licensing",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 3,
          capabilityName: "Sound FX",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 3,
          capabilityName: "Mixing",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 3,
          capabilityName: "Audio Post Production",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 4,
          capabilityName: "CGI",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 4,
          capabilityName: "In Engine",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 4,
          capabilityName: "Trailers",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 4,
          capabilityName: "Proprietary Engine",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 4,
          capabilityName: "Unreal",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 4,
          capabilityName: "Unity",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 5,
          capabilityName: "motion capture clean-up",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 6,
          capabilityName: "Dialogue",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 9,
          capabilityName: "Rigging",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 9,
          capabilityName: "Lighting",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 9,
          capabilityName: "Procedural",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 9,
          capabilityName: "Rendering",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 9,
          capabilityName: "Shaders",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 10,
          capabilityName: "UI",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 10,
          capabilityName: "UX",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 10,
          capabilityName: "Engine Integration",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 10,
          capabilityName: "Console",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 10,
          capabilityName: "Mobile",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 10,
          capabilityName: "Handheld",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 10,
          capabilityName: "Icons",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 10,
          capabilityName: "Research",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 11,
          capabilityName: "CGI",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 11,
          capabilityName: "In Engine",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 14,
          capabilityName: "General",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 14,
          capabilityName: "Proprietary Engine",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 14,
          capabilityName: "Unreal",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 14,
          capabilityName: "Unity",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 14,
          capabilityName: "Tools",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 14,
          capabilityName: "Optimization",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 14,
          capabilityName: "AI",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 14,
          capabilityName: "Proprietary",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 14,
          capabilityName: "Rendering",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 14,
          capabilityName: "Online Support",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 14,
          capabilityName: "Back End",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 14,
          capabilityName: "Multiplayer",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 15,
          capabilityName: "Game Engines",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 15,
          capabilityName: "Production",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 15,
          capabilityName: "Audio",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 15,
          capabilityName: "Review",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 15,
          capabilityName: "Game Engine",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 15,
          capabilityName: "Art",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 15,
          capabilityName: "Animation",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 15,
          capabilityName: "Anti Cheat",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 15,
          capabilityName: "Procedural Generation",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 15,
          capabilityName: "Level Creation",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 15,
          capabilityName: "Design",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 17,
          capabilityName: "Streaming",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 17,
          capabilityName: "PC",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 17,
          capabilityName: "Mobile",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 17,
          capabilityName: "Console",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 18,
          capabilityName: "Proprietary Engine",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 18,
          capabilityName: "Unreal",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 18,
          capabilityName: "Unity",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 18,
          capabilityName: "Mobile",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 18,
          capabilityName: "AR",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 18,
          capabilityName: "VR",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 18,
          capabilityName: "Art",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 20,
          capabilityName: "Level",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 20,
          capabilityName: "Combat",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 24,
          capabilityName: "Functional Testing",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 24,
          capabilityName: "Gameplay Testing",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 24,
          capabilityName: "Certification",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 24,
          capabilityName: "Hardware Certification",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 24,
          capabilityName: "Stress Testing",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 24,
          capabilityName: "Automated Testing",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 25,
          capabilityName: "Agency/Talent",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 25,
          capabilityName: "Managed Services",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 29,
          capabilityName: "Launch Campaigns",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 29,
          capabilityName: "Brand Identity",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 29,
          capabilityName: "Events",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 29,
          capabilityName: "Social Media",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 29,
          capabilityName: "Influencer",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 29,
          capabilityName: "Trailers",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 29,
          capabilityName: "Marketing Art",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 29,
          capabilityName: "Commercial/Video Production",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 30,
          capabilityName: "Website",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 30,
          capabilityName: "Ecommerce",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 30,
          capabilityName: "Stores",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 30,
          capabilityName: "Data Analytics",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          serviceId: 30,
          capabilityName: "Apps",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
      ],
    });

    const users = await prisma.users.createMany({
      data: [
        {
          email: "admin@gmail.com",
          firstName: "Admin",
          lastName: "Super",
          linkedInUrl: "test.com",
          approvalStatus: "approved",
          stripeCustomerId: "1234444444444444444",
          accessExpirationDate: "2025-01-22T10:11:00Z",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          email: "serviceprovider@test.com",
          firstName: "Service",
          lastName: "provider",
          linkedInUrl: "tesdt.com",
          approvalStatus: "approved",
          stripeCustomerId: "1234444444444444444",
          accessExpirationDate: "2025-01-22T10:11:00Z",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
      ],
    });

    const userroles = await prisma.userRoles.createMany({
      data: [
        {
          userId: 1,
          roleCode: "admin",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          userId: 2,
          roleCode: "service_provider",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
      ],
    });

    const companysizes = await prisma.companySizes.createMany({
      data: [
        {
          size: "0-10",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          size: "10-20",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          size: "20-50",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          size: "5-100",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          size: "100-500",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
      ],
    });
    const logoAssets = await prisma.assets.createMany({
      data: [
        {
          userId: 1,
          url: "https://i.pinimg.com/originals/82/c6/5b/82c65b9bb0a75026fc4c82a438b4cc9b.jpg",
          assetType: "image",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          userId: 2,
          url: "https://i.pinimg.com/originals/82/c6/5b/82c65b9bb0a75026fc4c82a438b4cc9b.jpg",
          assetType: "image",
          createdAt: currentDate,
          updatedAt: currentDate,
        },
      ],
    });
    const companies = await prisma.companies.createMany({
      data: [
        {
          userId: 1,
          name: "Aapthi",
          website: "appthi.com",
          shortDescription: "tested for tets company",
          companySize: 1,
          logoAssetId: 1,
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          userId: 2,
          name: "Serivice Company",
          website: "serviceappthi.com",
          shortDescription: "tested for tets service company",
          companySize: 1,
          logoAssetId: 1,
          createdAt: currentDate,
          updatedAt: currentDate,
        },
      ],
    });
    const servicesopt = await prisma.servicesOpt.createMany({
      data: [
        {
          companyId: 1,
          serviceId: 1,
          capabilityId: 1,
          createdAt: currentDate,
          updatedAt: currentDate,
        },
        {
          companyId: 2,
          serviceId: 2,
          capabilityId: 8,
          createdAt: currentDate,
          updatedAt: currentDate,
        },
      ],
    });
    console.log("Seed data created successfully");
  } catch (error) {
    console.error("Error seeding data:", error);
  } finally {
    await prisma.$disconnect();
  }
}

seedData().catch((error) => {
  console.error(error);
  process.exit(1);
});
